version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    network_mode: "host"
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: 'sample_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - "./scripts/init_dll.sql:/docker-entrypoint-initdb.d/1.sql"
volumes:
  my-db: